#### Basic TensorFlow

In [1]:
# Import module
import tensorflow as tf

In [2]:
# Create constant nodes with value
node1 = tf.constant(3.0, dtype=tf.float32)
node2 = tf.constant(4.0)
node3 = tf.constant([1, 2, 3, 4, 5, 6, 7])
node4 = tf.constant(-1.0, shape=[2, 3])
print(node1, node2, node3, node4)

Tensor("Const:0", shape=(), dtype=float32) Tensor("Const_1:0", shape=(), dtype=float32) Tensor("Const_2:0", shape=(7,), dtype=int32) Tensor("Const_3:0", shape=(2, 3), dtype=float32)


In [3]:
# Run session
sess = tf.Session()
print(sess.run([node1, node2]))
print(sess.run(node3))
print(sess.run(node4))

[3.0, 4.0]
[1 2 3 4 5 6 7]
[[-1. -1. -1.]
 [-1. -1. -1.]]


In [4]:
# Create a node by combining nodes
node5 = tf.add(node1, node2)
print(node5)
print(sess.run(node5))

Tensor("Add:0", shape=(), dtype=float32)
7.0


In [5]:
# Create empty placeholder deciding only dtype and waiting for input
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

# Use addition for creating node
adder_node = a + b
print(sess.run(adder_node, {a: 3, b: 4.5}))
print(sess.run(adder_node, {a: [1, 3], b: [2, 4]}))

7.5
[ 3.  7.]


In [6]:
# Use multiplication for creating node
add_and_triple = adder_node * 3
print(sess.run(add_and_triple, {a: 3, b: 4.5}))

22.5


In [7]:
# Create linear model
W = tf.Variable([.3], dtype=tf.float32)
b = tf.Variable([-.3], dtype=tf.float32)
x = tf.placeholder(tf.float32)

linear_model = W * x + b

# Reset(Initialize) variables
init = tf.global_variables_initializer()
sess.run(init)

print(sess.run(linear_model, {x: [1, 2, 3, 4]}))

[ 0.          0.30000001  0.60000002  0.90000004]


In [8]:
y = tf.placeholder(tf.float32)
squared_deltas = tf.square(linear_model - y)
loss = tf.reduce_sum(squared_deltas)
print(sess.run(loss, {x: [1, 2, 3, 4], y: [0, -1, -2, -3]}))

23.66


In [9]:
# tf.assign(ref, val): Update ref by assigning val
fixW = tf.assign(W, [-1.])
fixb = tf.assign(b, [1.])
sess.run([fixW, fixb])
print(sess.run(loss, {x: [1, 2, 3, 4], y: [0, -1, -2, -3]}))

0.0


In [10]:
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

sess.run(init)

for i in range(1000):
    sess.run(train, {x: [1, 2, 3, 4], y: [0, -1, -2, -3]})
    print(sess.run([W, b]))

[array([-0.21999997], dtype=float32), array([-0.456], dtype=float32)]
[array([-0.39679998], dtype=float32), array([-0.49552], dtype=float32)]
[array([-0.45961601], dtype=float32), array([-0.4965184], dtype=float32)]
[array([-0.48454273], dtype=float32), array([-0.48487374], dtype=float32)]
[array([-0.49684232], dtype=float32), array([-0.46917531], dtype=float32)]
[array([-0.50490189], dtype=float32), array([-0.45227283], dtype=float32)]
[array([-0.5115062], dtype=float32), array([-0.43511063], dtype=float32)]
[array([-0.51758033], dtype=float32), array([-0.41800055], dtype=float32)]
[array([-0.52343202], dtype=float32), array([-0.40104443], dtype=float32)]
[array([-0.52916396], dtype=float32), array([-0.38427448], dtype=float32)]
[array([-0.53481066], dtype=float32), array([-0.36769974], dtype=float32)]
[array([-0.54038435], dtype=float32), array([-0.35132164], dtype=float32)]
[array([-0.54588938], dtype=float32), array([-0.33513904], dtype=float32)]
[array([-0.55132794], dtype=float32

[array([-0.91178066], dtype=float32), array([ 0.74062449], dtype=float32)]
[array([-0.91283715], dtype=float32), array([ 0.74373066], dtype=float32)]
[array([-0.913881], dtype=float32), array([ 0.74679965], dtype=float32)]
[array([-0.91491234], dtype=float32), array([ 0.74983186], dtype=float32)]
[array([-0.91593128], dtype=float32), array([ 0.75282776], dtype=float32)]
[array([-0.91693807], dtype=float32), array([ 0.75578779], dtype=float32)]
[array([-0.91793281], dtype=float32), array([ 0.75871235], dtype=float32)]
[array([-0.91891557], dtype=float32), array([ 0.76160192], dtype=float32)]
[array([-0.91988659], dtype=float32), array([ 0.76445687], dtype=float32)]
[array([-0.92084599], dtype=float32), array([ 0.76727766], dtype=float32)]
[array([-0.92179394], dtype=float32), array([ 0.77006465], dtype=float32)]
[array([-0.92273051], dtype=float32), array([ 0.77281827], dtype=float32)]
[array([-0.92365587], dtype=float32), array([ 0.77553892], dtype=float32)]
[array([-0.92457014], dtype

[array([-0.98326981], dtype=float32), array([ 0.95081121], dtype=float32)]
[array([-0.98347014], dtype=float32), array([ 0.95140028], dtype=float32)]
[array([-0.98366809], dtype=float32), array([ 0.95198226], dtype=float32)]
[array([-0.98386371], dtype=float32), array([ 0.95255733], dtype=float32)]
[array([-0.98405695], dtype=float32), array([ 0.95312548], dtype=float32)]
[array([-0.98424786], dtype=float32), array([ 0.95368683], dtype=float32)]
[array([-0.98443651], dtype=float32), array([ 0.95424145], dtype=float32)]
[array([-0.9846229], dtype=float32), array([ 0.95478946], dtype=float32)]
[array([-0.98480707], dtype=float32), array([ 0.95533091], dtype=float32)]
[array([-0.98498899], dtype=float32), array([ 0.95586586], dtype=float32)]
[array([-0.98516876], dtype=float32), array([ 0.95639437], dtype=float32)]
[array([-0.98534638], dtype=float32), array([ 0.95691657], dtype=float32)]
[array([-0.98552185], dtype=float32), array([ 0.95743251], dtype=float32)]
[array([-0.98569524], dtyp

[array([-0.99711877], dtype=float32), array([ 0.99152887], dtype=float32)]
[array([-0.99715328], dtype=float32), array([ 0.99163032], dtype=float32)]
[array([-0.99718738], dtype=float32), array([ 0.99173057], dtype=float32)]
[array([-0.99722105], dtype=float32), array([ 0.99182957], dtype=float32)]
[array([-0.99725431], dtype=float32), array([ 0.99192744], dtype=float32)]
[array([-0.99728721], dtype=float32), array([ 0.99202412], dtype=float32)]
[array([-0.9973197], dtype=float32), array([ 0.99211961], dtype=float32)]
[array([-0.99735177], dtype=float32), array([ 0.99221396], dtype=float32)]
[array([-0.99738348], dtype=float32), array([ 0.99230719], dtype=float32)]
[array([-0.99741483], dtype=float32), array([ 0.99239928], dtype=float32)]
[array([-0.99744576], dtype=float32), array([ 0.99249029], dtype=float32)]
[array([-0.99747634], dtype=float32), array([ 0.99258024], dtype=float32)]
[array([-0.99750656], dtype=float32), array([ 0.99266911], dtype=float32)]
[array([-0.99753642], dtyp

[array([-0.99949783], dtype=float32), array([ 0.99852359], dtype=float32)]
[array([-0.99950385], dtype=float32), array([ 0.9985413], dtype=float32)]
[array([-0.99950981], dtype=float32), array([ 0.99855876], dtype=float32)]
[array([-0.99951565], dtype=float32), array([ 0.99857605], dtype=float32)]
[array([-0.99952149], dtype=float32), array([ 0.99859309], dtype=float32)]
[array([-0.99952722], dtype=float32), array([ 0.99860996], dtype=float32)]
[array([-0.99953288], dtype=float32), array([ 0.99862659], dtype=float32)]
[array([-0.99953848], dtype=float32), array([ 0.99864304], dtype=float32)]
[array([-0.99954402], dtype=float32), array([ 0.99865931], dtype=float32)]
[array([-0.99954951], dtype=float32), array([ 0.99867535], dtype=float32)]
[array([-0.99955487], dtype=float32), array([ 0.9986912], dtype=float32)]
[array([-0.99956018], dtype=float32), array([ 0.99870688], dtype=float32)]
[array([-0.99956542], dtype=float32), array([ 0.99872237], dtype=float32)]
[array([-0.99957061], dtype

[array([-0.99990243], dtype=float32), array([ 0.99971318], dtype=float32)]
[array([-0.99990362], dtype=float32), array([ 0.99971664], dtype=float32)]
[array([-0.99990475], dtype=float32), array([ 0.99972004], dtype=float32)]
[array([-0.99990588], dtype=float32), array([ 0.99972337], dtype=float32)]
[array([-0.99990702], dtype=float32), array([ 0.99972665], dtype=float32)]
[array([-0.99990815], dtype=float32), array([ 0.99972993], dtype=float32)]
[array([-0.99990922], dtype=float32), array([ 0.99973315], dtype=float32)]
[array([-0.9999103], dtype=float32), array([ 0.99973637], dtype=float32)]
[array([-0.99991137], dtype=float32), array([ 0.99973953], dtype=float32)]
[array([-0.99991244], dtype=float32), array([ 0.99974263], dtype=float32)]
[array([-0.99991351], dtype=float32), array([ 0.99974573], dtype=float32)]
[array([-0.99991453], dtype=float32), array([ 0.99974877], dtype=float32)]
[array([-0.99991554], dtype=float32), array([ 0.99975175], dtype=float32)]
[array([-0.99991655], dtyp

[array([-0.99998164], dtype=float32), array([ 0.99994612], dtype=float32)]
[array([-0.99998188], dtype=float32), array([ 0.99994677], dtype=float32)]
[array([-0.99998212], dtype=float32), array([ 0.99994743], dtype=float32)]
[array([-0.99998236], dtype=float32), array([ 0.99994808], dtype=float32)]
[array([-0.99998254], dtype=float32), array([ 0.99994874], dtype=float32)]
[array([-0.99998277], dtype=float32), array([ 0.99994934], dtype=float32)]
[array([-0.99998295], dtype=float32), array([ 0.99994993], dtype=float32)]
[array([-0.99998313], dtype=float32), array([ 0.99995053], dtype=float32)]
[array([-0.99998337], dtype=float32), array([ 0.99995112], dtype=float32)]
[array([-0.99998355], dtype=float32), array([ 0.99995172], dtype=float32)]
[array([-0.99998379], dtype=float32), array([ 0.99995232], dtype=float32)]
[array([-0.99998397], dtype=float32), array([ 0.99995291], dtype=float32)]
[array([-0.9999842], dtype=float32), array([ 0.99995345], dtype=float32)]
[array([-0.99998438], dtyp

[array([-0.99999547], dtype=float32), array([ 0.99998671], dtype=float32)]
[array([-0.99999553], dtype=float32), array([ 0.99998689], dtype=float32)]
[array([-0.99999559], dtype=float32), array([ 0.99998707], dtype=float32)]
[array([-0.99999565], dtype=float32), array([ 0.99998719], dtype=float32)]
[array([-0.99999571], dtype=float32), array([ 0.99998736], dtype=float32)]
[array([-0.99999577], dtype=float32), array([ 0.99998754], dtype=float32)]
[array([-0.99999583], dtype=float32), array([ 0.99998772], dtype=float32)]
[array([-0.99999589], dtype=float32), array([ 0.9999879], dtype=float32)]
[array([-0.99999595], dtype=float32), array([ 0.99998802], dtype=float32)]
[array([-0.99999601], dtype=float32), array([ 0.99998814], dtype=float32)]
[array([-0.99999601], dtype=float32), array([ 0.99998832], dtype=float32)]
[array([-0.99999607], dtype=float32), array([ 0.99998844], dtype=float32)]
[array([-0.99999613], dtype=float32), array([ 0.99998856], dtype=float32)]
[array([-0.99999619], dtyp

### Recognize hand writing

In [11]:
from tensorflow.examples.tutorials.mnist import input_data

In [12]:
# Download MNIST dataset
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


In [13]:
# Define variables of a linear model (W * x + b)
W = tf.Variable(tf.zeros([784, 10]))
b = tf.Variable(tf.zeros([10]))
x = tf.placeholder(tf.float32, [None, 784])

In [14]:
y = tf.nn.softmax(tf.matmul(x, W) + b)

y_ = tf.placeholder(tf.float32, [None, 10])

cross_entropy = tf.reduce_mean(-tf.reduce_sum(y_ * tf.log(y), reduction_indices=[1]))

train_step = tf.train.AdamOptimizer(0.5).minimize(cross_entropy)

In [15]:
# Reset session
sess = tf.InteractiveSession()

tf.global_variables_initializer().run()

# Run by mini batch
for _ in range(1000):
    batch_xs, batch_ys = mnist.train.next_batch(100)
    sess.run(train_step, feed_dict={x: batch_xs, y_: batch_ys})

In [16]:
correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(y, -1))

accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

print(sess.run(accuracy, feed_dict={x: mnist.test.images, y_: mnist.test.labels}))

1.0
